### ISSUE TITLE
Some puzzles

### ISSUE THREAD

**Issue by CSSandHTMLonly** [tititogepi/Tititogepi-memo#5]
Atomic 960:
https://www.pychess.org/PNmqxqt6?ply=36 - mate in 4
https://www.pychess.org/YFN7Ihll?ply=12

Random makruk puzzle fen: 6r1/5nr1/4R2R/p1kp4/8/1PP1M2K/8/8 w - - 0 1

**Comment by CSSandHTMLonly** [comment]
Also, here's a makruk puzzles, the tactic is from lichess but I've are applied on makruk!
6r1/5nr1/4R2R/p1kp4/8/1PP1M2K/8/8 w - - 0 1

**Comment by ttBOT-on-Lichess** [comment]
Thanks a lot!
For the 1st puzzle, I've take the move after because there were many mate in 4 possible
The 2nd is perfect! Same for the 3rd! :)
